require('dotenv').config();
const mongoose = require('mongoose');
const User          = require('./models/User');
const Restaurant    = require('./models/Restaurant');
const MenuItem      = require('./models/MenuItem');
const DeliveryAgent = require('./models/DeliveryAgent');

mongoose.connect(process.env.MONGODB_URI)
  .then(() => console.log('Connected to MongoDB'))
  .catch(err => { console.error(err); process.exit(1); });

const seed = async () => {
  try {
    await User.deleteMany({});
    await Restaurant.deleteMany({});
    await MenuItem.deleteMany({});
    await DeliveryAgent.deleteMany({});

    const admin = await User.create({ name: 'Admin HungryBirds', email: 'admin@hungrybirds.com', phone: '9000000000', password: 'admin123', role: 'admin' });
    await User.create({ name: 'Ravi Kumar', email: 'test@test.com', phone: '9876543210', password: 'test123', role: 'customer' });
    console.log('✅ Users created');

    const [renuka, newtaj, pedha, adarsha, udupi, ajanta, tandoor, shahi, comfort, dasaprakash, sweetcravings] = await Restaurant.insertMany([
      { name: 'Hotel Shree Renuka',          image: 'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300879/legends11_294ccb61819ddec916d428142fcb695d_accmd2.jpg',                                                                      cuisine: ['South Indian','North Indian'],           address: 'Sadashivanagar, Dharwad', location: { type:'Point', coordinates:[75.0078,15.4589] }, rating:4.3, totalRatings:320, deliveryTime:'25-35 mins', deliveryFee:20, minimumOrder:80,  isOpen:true, offers:['10% off above ₹150'],             ownerId:admin._id },
      { name: 'New Taj Hotel',               image: 'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300849/original_rcriyg.jpg',                                                                                                        cuisine: ['North Indian','Mughlai','Biryani'],      address: 'Court Circle, Dharwad',   location: { type:'Point', coordinates:[75.0134,15.4612] }, rating:4.5, totalRatings:540, deliveryTime:'30-45 mins', deliveryFee:30, minimumOrder:120, isOpen:true, offers:['Free raita above ₹250'],          ownerId:admin._id },
      { name: 'Dharwad Pedha Sweet House',   image: 'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301116/261_stoaw7.jpg',                                                                                                             cuisine: ['Sweets','Snacks','South Indian'],        address: 'Station Road, Dharwad',   location: { type:'Point', coordinates:[75.0089,15.4601] }, rating:4.7, totalRatings:890, deliveryTime:'20-30 mins', deliveryFee:15, minimumOrder:50,  isOpen:true, offers:['Buy 2 get 1 free on Pedha'],      ownerId:admin._id },
      { name: 'Hotel Adarsha',               image: 'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301162/hotel-providence-paris-restaurant-main_ybif3p.jpg',                                                                         cuisine: ['Biryani','Kebab','North Indian'],        address: 'PB Road, Dharwad',        location: { type:'Point', coordinates:[75.0056,15.4578] }, rating:4.4, totalRatings:670, deliveryTime:'35-45 mins', deliveryFee:30, minimumOrder:150, isOpen:true, offers:['15% off on first order'],         ownerId:admin._id },
      { name: 'Udupi Krishna Bhavan',        image: 'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300716/1-5_fbib8y.png',                                                                                                             cuisine: ['South Indian','Tiffin','Juices'],        address: 'Kalyan Nagar, Dharwad',   location: { type:'Point', coordinates:[75.0023,15.4545] }, rating:4.2, totalRatings:410, deliveryTime:'20-30 mins', deliveryFee:20, minimumOrder:60,  isOpen:true, offers:['Free coffee above ₹100'],         ownerId:admin._id },
      { name: 'Hotel Ajanta',                image: 'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300840/2025-04-17-JeremyClark-ReadMcKendree-0182_V1-1600x1146_lpddsi.jpg',                                                         cuisine: ['North Indian','South Indian','Chinese'], address: 'Lamington Road, Hubli',   location: { type:'Point', coordinates:[75.1240,15.3647] }, rating:4.3, totalRatings:560, deliveryTime:'30-40 mins', deliveryFee:30, minimumOrder:100, isOpen:true, offers:['20% off above ₹300'],             ownerId:admin._id },
      { name: 'Tandoor Restaurant',          image: 'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300833/Cinco-de-Mayo-8_8271E7A1-A096-C430-7911A4B232BC2E06-8271df310a866d5_8271f421-f4f6-0998-a7fbd9c17ced7598_yq3ywt.jpg',       cuisine: ['North Indian','Tandoor','Kebab'],        address: 'Keshwapur, Hubli',        location: { type:'Point', coordinates:[75.1198,15.3712] }, rating:4.6, totalRatings:720, deliveryTime:'35-50 mins', deliveryFee:40, minimumOrder:200, isOpen:true, offers:['Free naan above ₹400'],           ownerId:admin._id },
      { name: 'Shahi Biryani Center',        image: 'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300840/2025-04-17-JeremyClark-ReadMcKendree-0182_V1-1600x1146_lpddsi.jpg',                                                         cuisine: ['Biryani','Mughlai','Kebab'],             address: 'Vidyanagar, Hubli',        location: { type:'Point', coordinates:[75.1356,15.3698] }, rating:4.5, totalRatings:830, deliveryTime:'30-45 mins', deliveryFee:30, minimumOrder:150, isOpen:true, offers:['10% off above ₹250'],             ownerId:admin._id },
      { name: 'Comfort Zone Cafe',           image: 'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300837/blb12075_47901722071_o.jpg_imvu7x.jpg',                                                                                      cuisine: ['Fast Food','Burgers','Pizza','Shakes'],  address: 'Club Road, Hubli',        location: { type:'Point', coordinates:[75.1289,15.3625] }, rating:4.1, totalRatings:390, deliveryTime:'25-35 mins', deliveryFee:25, minimumOrder:100, isOpen:true, offers:['Free fries above ₹200'],          ownerId:admin._id },
      { name: 'Hotel Dasaprakash',           image: 'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300843/Mr_Gatti_s_Walmart_1716_b5qxmi.jpg',                                                                                        cuisine: ['South Indian','Tiffin','Meals'],         address: 'Desai Cross, Hubli',       location: { type:'Point', coordinates:[75.1312,15.3658] }, rating:4.4, totalRatings:610, deliveryTime:'20-35 mins', deliveryFee:20, minimumOrder:80,  isOpen:true, offers:['Free sambar above ₹150'],         ownerId:admin._id },
      { name: 'Sweet Cravings Dessert Cafe', image: 'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301116/261_stoaw7.jpg',                                                                                                             cuisine: ['Desserts','Ice Cream','Waffles','Shakes'],address: 'College Road, Dharwad',  location: { type:'Point', coordinates:[75.0110,15.4620] }, rating:4.6, totalRatings:280, deliveryTime:'20-30 mins', deliveryFee:20, minimumOrder:80,  isOpen:true, offers:['Free ice cream scoop above ₹300'], ownerId:admin._id },
    ]);
    console.log('✅ 11 Restaurants created');

    await MenuItem.insertMany([
      // ── Hotel Shree Renuka ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      { restaurantId:renuka._id,        name:'Masala Dosa',                    description:'Crispy dosa with spicy potato filling',                  price:60,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300139/masala-dosa-recipe-500x500_kza8wn.jpg',                                                                                  category:'Tiffin',    isVeg:true,  isBestseller:true  },
      { restaurantId:renuka._id,        name:'Idli Sambar (3 pcs)',            description:'Soft steamed idlis with sambar and chutney',             price:50,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773298690/Soft-Idlis-made-from-idli-dosa-batter-2_pzgag2.jpg',                                                                       category:'Tiffin',    isVeg:true,  isBestseller:true  },
      { restaurantId:renuka._id,        name:'Vada (2 pcs)',                   description:'Crispy medu vada with sambar and chutney',               price:40,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302621/hq720_aqchcj.jpg',                                                                                                         category:'Tiffin',    isVeg:true,  isBestseller:false },
      { restaurantId:renuka._id,        name:'Full Meals',                     description:'Rice, sambar, rasam, 2 curries, papad, pickle',          price:120, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300382/a94a23_aa674298181e422db3f4da9c8bfac4cc_mv2_olsx1w.jpg',                                                                   category:'Meals',     isVeg:true,  isBestseller:true  },
      { restaurantId:renuka._id,        name:'Filter Coffee',                  description:'Strong South Indian filter coffee',                      price:30,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301707/Corkframes_Coffee_Guide_520x500_422ebe38-4cfa-42b5-a266-b9bfecabaf30_faipdi.jpg',                                            category:'Drinks',    isVeg:true,  isBestseller:false },
      // ── New Taj Hotel ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      { restaurantId:newtaj._id,        name:'Chicken Tikka',                  description:'Juicy chicken marinated in spices and grilled',          price:180, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300428/lamb-shish-kebab-20-500x500_zvgxfn.jpg',                                                                                    category:'Starters',  isVeg:false, isBestseller:true  },
      { restaurantId:newtaj._id,        name:'Paneer Tikka',                   description:'Soft paneer cubes marinated and grilled',                price:160, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300400/gobi-manchurian_fvajo1.webp',                                                                                               category:'Starters',  isVeg:true,  isBestseller:true  },
      { restaurantId:newtaj._id,        name:'Butter Chicken',                 description:'Tender chicken in rich creamy tomato gravy',             price:220, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300395/Gobi-Manchurian-HOHV_ytvwla.jpg',                                                                                          category:'Main Course',isVeg:false, isBestseller:true  },
      { restaurantId:newtaj._id,        name:'Paneer Butter Masala',           description:'Soft paneer in rich buttery tomato gravy',               price:200, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300313/Dal-Makhani-1_u8flhz.jpg',                                                                                                 category:'Main Course',isVeg:true,  isBestseller:false },
      { restaurantId:newtaj._id,        name:'Dal Makhani',                    description:'Slow cooked black dal with cream and butter',            price:160, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300308/dal-makhani-recipe_cy9iqw.webp',                                                                                           category:'Main Course',isVeg:true,  isBestseller:false },
      { restaurantId:newtaj._id,        name:'Butter Naan',                    description:'Soft leavened bread with butter',                        price:40,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300328/butter-naan_ptfp5g.jpg',                                                                                                   category:'Breads',    isVeg:true,  isBestseller:false },
      { restaurantId:newtaj._id,        name:'Chicken Biryani',                description:'Aromatic basmati rice with tender chicken pieces',       price:220, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300244/chicken-biriyani_jhndxx.jpg',                                                                                               category:'Biryani',   isVeg:false, isBestseller:true  },
      // ── Dharwad Pedha Sweet House ───────────────────────────────────────────────────────────────────────────────────────────────────────────
      { restaurantId:pedha._id,         name:'Dharwad Pedha (250g)',           description:'Famous Dharwad special milk pedha',                      price:120, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773298631/ASSORTEDSWEETS_2_1_bubvw8.png',                                                                                            category:'Sweets',    isVeg:true,  isBestseller:true  },
      { restaurantId:pedha._id,         name:'Gulab Jamun (6 pcs)',            description:'Soft milk solid balls in sugar syrup',                   price:60,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301665/soft-gulab-jamun-recipe-for-raksha-bandhan-from-dough-to-syrup-all-you-need-to-know_u5evtg.webp',                           category:'Sweets',    isVeg:true,  isBestseller:false },
      { restaurantId:pedha._id,         name:'Jalebi (250g)',                  description:'Crispy spiral sweets soaked in sugar syrup',             price:80,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301670/53099699_ceim4l.jpg',                                                                                                      category:'Sweets',    isVeg:true,  isBestseller:true  },
      { restaurantId:pedha._id,         name:'Mirchi Bajji (4 pcs)',           description:'Spicy green chilli fritters',                            price:40,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302774/mirchi-bajji-mirapakaya-bajji-recipe_suiqnk.jpg',                                                                           category:'Snacks',    isVeg:true,  isBestseller:false },
      { restaurantId:pedha._id,         name:'Samosa (2 pcs)',                 description:'Crispy pastry with spicy potato filling',                price:30,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301677/samosa-recipe_mwa4hq.jpg',                                                                                                 category:'Snacks',    isVeg:true,  isBestseller:false },
      // ── Hotel Adarsha ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      { restaurantId:adarsha._id,       name:'Chicken Dum Biryani',            description:'Slow cooked aromatic chicken biryani',                   price:200, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300231/Tandoori_Chicken_Biriyani_-_Raw_1_30-e1612009020739_ix9y8o.jpg',                                                           category:'Biryani',   isVeg:false, isBestseller:true  },
      { restaurantId:adarsha._id,       name:'Mutton Biryani',                 description:'Tender mutton pieces in fragrant basmati rice',          price:260, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300241/how-to-make-kerala-style-pressure-cooker-chicken-biriyani_zpj0nn.jpg',                                                      category:'Biryani',   isVeg:false, isBestseller:true  },
      { restaurantId:adarsha._id,       name:'Veg Biryani',                    description:'Mixed vegetables in aromatic basmati rice',              price:160, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300238/500-x-380-Biryani_yfoboe.png',                                                                                             category:'Biryani',   isVeg:true,  isBestseller:false },
      { restaurantId:adarsha._id,       name:'Raita',                          description:'Fresh yogurt with cucumber and spices',                  price:40,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302600/How-to-Make-Buttermilk-4_mwr9vy.jpg',                                                                                      category:'Sides',     isVeg:true,  isBestseller:false },
      // ── Udupi Krishna Bhavan ────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      { restaurantId:udupi._id,         name:'Plain Dosa',                     description:'Thin crispy rice and lentil crepe',                      price:40,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300137/Dosa-Recipe-Step-By-Step-Instructions-scaled_cemgf0.jpg',                                                                   category:'Tiffin',    isVeg:true,  isBestseller:false },
      { restaurantId:udupi._id,         name:'Rava Idli (3 pcs)',              description:'Soft semolina idlis with sambar and chutney',            price:60,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773298690/Soft-Idlis-made-from-idli-dosa-batter-2_pzgag2.jpg',                                                                       category:'Tiffin',    isVeg:true,  isBestseller:true  },
      { restaurantId:udupi._id,         name:'Pongal',                         description:'Creamy rice and moong dal with ghee and pepper',         price:60,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302722/pongal-ven-pongal_f4djwk.webp',                                                                                            category:'Tiffin',    isVeg:true,  isBestseller:false },
      { restaurantId:udupi._id,         name:'Mango Lassi',                    description:'Fresh mango blended with yogurt',                        price:60,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300280/health-benefits-of-mango-juice-GettyImages-1147373774-f7ebf4e4c13f4f67a2420df3c4325a04_s1ghxx.jpg',                          category:'Drinks',    isVeg:true,  isBestseller:true  },
      { restaurantId:udupi._id,         name:'Fresh Lime Juice',               description:'Chilled fresh lime with sugar and salt',                 price:40,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300291/5-super-powered-fresh-juice-and-smoothie-recipes.jpg_ujm5vj.webp',                                                          category:'Drinks',    isVeg:true,  isBestseller:false },
      // ── Hotel Ajanta ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      { restaurantId:ajanta._id,        name:'Gobi Manchurian',                description:'Crispy cauliflower in spicy Chinese sauce',              price:120, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300401/maxresdefault_bz7vju.jpg',                                                                                                  category:'Starters',  isVeg:true,  isBestseller:true  },
      { restaurantId:ajanta._id,        name:'Chicken 65',                     description:'Spicy deep fried chicken appetizer',                     price:160, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300400/gobi-manchurian_fvajo1.webp',                                                                                               category:'Starters',  isVeg:false, isBestseller:true  },
      { restaurantId:ajanta._id,        name:'Veg Fried Rice',                 description:'Wok tossed rice with mixed vegetables',                  price:120, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302380/Fried-Rice-Heart-Naptime-11_t1eoci.jpg',                                                                                   category:'Main Course',isVeg:true,  isBestseller:false },
      { restaurantId:ajanta._id,        name:'Chicken Fried Rice',             description:'Wok tossed rice with chicken and vegetables',            price:150, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302376/k_2FPhoto_2FSeries_2F2020-04-snapshot-cooking-5-recipes-to-make-with-2-cups-of-rice_2Fthekitchn-pork-fried-rice-beauty_70361c_landscape_jc0smk.jpg', category:'Main Course',isVeg:false, isBestseller:true  },
      { restaurantId:ajanta._id,        name:'Paneer Tikka Masala',            description:'Grilled paneer in spicy onion tomato gravy',             price:190, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301768/Healthy-Paneer-Tikka-Masala-recipe_svewqo.jpg',                                                                            category:'Main Course',isVeg:true,  isBestseller:false },
      // ── Tandoor Restaurant ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      { restaurantId:tandoor._id,       name:'Seekh Kebab',                    description:'Minced meat with spices grilled on skewers',             price:200, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773298837/Kabab-torsh-with-salad-Shirazi-charred-onion-yogurt-1-1024x683_e0kdjv.jpg',                                                  category:'Starters',  isVeg:false, isBestseller:true  },
      { restaurantId:tandoor._id,       name:'Hara Bhara Kebab',               description:'Spinach and potato patties grilled in tandoor',          price:150, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302417/aw-lamb-kebabs-jumbo_mq4ghn.jpg',                                                                                          category:'Starters',  isVeg:true,  isBestseller:false },
      { restaurantId:tandoor._id,       name:'Mutton Rogan Josh',              description:'Slow cooked mutton in aromatic Kashmiri gravy',          price:280, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302413/lamb-shish-kebab-20_g55xnu.jpg',                                                                                           category:'Main Course',isVeg:false, isBestseller:true  },
      { restaurantId:tandoor._id,       name:'Shahi Paneer',                   description:'Paneer in rich creamy royal gravy',                      price:200, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302904/52446409_iu2onb.jpg',                                                                                                      category:'Main Course',isVeg:true,  isBestseller:false },
      { restaurantId:tandoor._id,       name:'Garlic Naan',                    description:'Soft naan topped with garlic and butter',                price:50,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300343/butter-naan_rrdd9l.jpg',                                                                                                   category:'Breads',    isVeg:true,  isBestseller:true  },
      // ── Shahi Biryani Center ────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      { restaurantId:shahi._id,         name:'Special Chicken Biryani',        description:'House special chicken biryani with secret spices',       price:230, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300225/chettinadu-chicken-biriyani-1-3_arm8vz.jpg',                                                                                category:'Biryani',   isVeg:false, isBestseller:true  },
      { restaurantId:shahi._id,         name:'Egg Biryani',                    description:'Flavorful biryani with boiled eggs',                     price:170, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302608/egg-biryani-3-1-850x1275_qjs30l.jpg',                                                                                      category:'Biryani',   isVeg:false, isBestseller:false },
      { restaurantId:shahi._id,         name:'Paneer Biryani',                 description:'Fragrant biryani with soft paneer pieces',               price:190, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302789/Achari-Paneer-Biryani-Featured_oimilc.jpg',                                                                                category:'Biryani',   isVeg:true,  isBestseller:true  },
      { restaurantId:shahi._id,         name:'Mirchi Ka Salan',                description:'Spicy chilli curry served with biryani',                 price:60,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302916/Mirchi-Ka-Salan_final3-1_rlpigd.jpg',                                                                                      category:'Sides',     isVeg:true,  isBestseller:false },
      // ── Comfort Zone Cafe ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      { restaurantId:comfort._id,       name:'Veg Burger',                     description:'Crispy veg patty with lettuce and sauce',                price:80,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300206/c8788b46-aadf-4bd5-9b38-3f2865e6c728_fcvg6m.jpg',                                                                          category:'Burgers',   isVeg:true,  isBestseller:false },
      { restaurantId:comfort._id,       name:'Chicken Burger',                 description:'Juicy chicken patty with cheese and sauce',              price:120, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300194/MSG-Smash-Burger-FT-RECIPE0124-d9682401f3554ef683e24311abdf342b_wtrsgm.jpg',                                                category:'Burgers',   isVeg:false, isBestseller:true  },
      { restaurantId:comfort._id,       name:'Margherita Pizza',               description:'Classic cheese and tomato pizza',                        price:180, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300167/tomato-mozzarella-pizza-FT-RECIPE0725-e7244e979c504188a049623668c15b2e_rs3lua.jpg',                                          category:'Pizza',     isVeg:true,  isBestseller:true  },
      { restaurantId:comfort._id,       name:'Chicken Tikka Pizza',            description:'Pizza topped with spicy chicken tikka',                  price:220, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300178/Easy-Hawaiian-Pizza_EXPS_TOHVP24_276179_MR_03_27_2_jhusrw.jpg',                                                            category:'Pizza',     isVeg:false, isBestseller:false },
      { restaurantId:comfort._id,       name:'Chocolate Shake',                description:'Rich creamy chocolate milkshake',                        price:80,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302389/Brownie-Milkshake-Recipe-20-scaled_a3eoac.jpg',                                                                            category:'Shakes',    isVeg:true,  isBestseller:true  },
      { restaurantId:comfort._id,       name:'Strawberry Shake',               description:'Fresh strawberry blended with ice cream',                price:90,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300274/watermelon-juice-1_yyw88n.jpg',                                                                                            category:'Shakes',    isVeg:true,  isBestseller:false },
      // ── Hotel Dasaprakash ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
      { restaurantId:dasaprakash._id,   name:'Set Dosa (3 pcs)',               description:'Soft spongy dosas with sambar and chutney',              price:60,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300144/28KITCHEN1-jumbo_rz4qfz.jpg',                                                                                               category:'Tiffin',    isVeg:true,  isBestseller:true  },
      { restaurantId:dasaprakash._id,   name:'Poori Bhaji (3 pcs)',            description:'Fluffy pooris with spicy potato bhaji',                  price:70,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302736/8397316064_b13c0d47b9_o_hgxc87.jpg',                                                                                       category:'Tiffin',    isVeg:true,  isBestseller:false },
      { restaurantId:dasaprakash._id,   name:'Veg Thali',                      description:'Complete meal with rice, dal, sabzi, roti, papad',       price:130, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300379/11128282834_dfba237cd1_o_wrz3eh.jpg',                                                                                      category:'Meals',     isVeg:true,  isBestseller:true  },
      { restaurantId:dasaprakash._id,   name:'South Indian Meals',             description:'Rice, sambar, rasam, 3 curries, curd, papad',            price:110, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773300376/9634876480_20d7ac8196_o_oigwex.jpg',                                                                                       category:'Meals',     isVeg:true,  isBestseller:false },
      { restaurantId:dasaprakash._id,   name:'Buttermilk',                     description:'Fresh chilled spiced buttermilk',                        price:25,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302595/Blog_1_ohkzgz.jpg',                                                                                                        category:'Drinks',    isVeg:true,  isBestseller:false },
      { restaurantId:dasaprakash._id,   name:'Filter Coffee',                  description:'Strong South Indian filter coffee',                      price:30,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302748/Filter_1500x_y4vw2q.jpg',                                                                                                  category:'Drinks',    isVeg:true,  isBestseller:false },
      // ── Sweet Cravings Dessert Cafe ─────────────────────────────────────────────────────────────────────────────────────────────────────────
      { restaurantId:sweetcravings._id, name:'Chocolate Ice Cream (2 scoops)', description:'Rich creamy chocolate ice cream',                        price:80,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301116/261_stoaw7.jpg',                                                                                                            category:'Ice Cream', isVeg:true,  isBestseller:true  },
      { restaurantId:sweetcravings._id, name:'Butterscotch Sundae',            description:'Butterscotch ice cream with caramel sauce and nuts',     price:120, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301116/261_stoaw7.jpg',                                                                                                            category:'Ice Cream', isVeg:true,  isBestseller:true  },
      { restaurantId:sweetcravings._id, name:'Strawberry Ice Cream (2 scoops)',description:'Fresh strawberry flavored ice cream',                    price:80,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301116/261_stoaw7.jpg',                                                                                                            category:'Ice Cream', isVeg:true,  isBestseller:false },
      { restaurantId:sweetcravings._id, name:'Nutella Waffle',                 description:'Crispy waffle topped with Nutella and banana',           price:150, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301116/261_stoaw7.jpg',                                                                                                            category:'Waffles',   isVeg:true,  isBestseller:true  },
      { restaurantId:sweetcravings._id, name:'Fruit Waffle',                   description:'Crispy waffle topped with fresh fruits and cream',       price:140, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301116/261_stoaw7.jpg',                                                                                                            category:'Waffles',   isVeg:true,  isBestseller:false },
      { restaurantId:sweetcravings._id, name:'Oreo Shake',                     description:'Creamy milkshake blended with Oreo cookies',             price:100, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302389/Brownie-Milkshake-Recipe-20-scaled_a3eoac.jpg',                                                                            category:'Shakes',    isVeg:true,  isBestseller:true  },
      { restaurantId:sweetcravings._id, name:'KitKat Shake',                   description:'Rich chocolate shake with KitKat pieces',                price:110, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773302389/Brownie-Milkshake-Recipe-20-scaled_a3eoac.jpg',                                                                            category:'Shakes',    isVeg:true,  isBestseller:false },
      { restaurantId:sweetcravings._id, name:'Chocolate Truffle Cake (slice)', description:'Rich dark chocolate truffle cake slice',                 price:120, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301116/261_stoaw7.jpg',                                                                                                            category:'Cakes',     isVeg:true,  isBestseller:true  },
      { restaurantId:sweetcravings._id, name:'Red Velvet Cake (slice)',        description:'Soft red velvet cake with cream cheese frosting',        price:130, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301116/261_stoaw7.jpg',                                                                                                            category:'Cakes',     isVeg:true,  isBestseller:false },
      { restaurantId:sweetcravings._id, name:'Kulfi Falooda',                  description:'Traditional Indian kulfi with falooda noodles',          price:100, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301116/261_stoaw7.jpg',                                                                                                            category:'Desserts',  isVeg:true,  isBestseller:true  },
      { restaurantId:sweetcravings._id, name:'Brownie with Ice Cream',         description:'Warm chocolate brownie with vanilla ice cream',          price:140, image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301116/261_stoaw7.jpg',                                                                                                            category:'Desserts',  isVeg:true,  isBestseller:true  },
      { restaurantId:sweetcravings._id, name:'Gulab Jamun (4 pcs)',            description:'Soft milk solid balls soaked in sugar syrup',            price:60,  image:'https://res.cloudinary.com/dzx9gfdeo/image/upload/v1773301665/soft-gulab-jamun-recipe-for-raksha-bandhan-from-dough-to-syrup-all-you-need-to-know_u5evtg.webp',                           category:'Desserts',  isVeg:true,  isBestseller:false },
    ]);
    console.log('✅ 67 Menu items created');

    await DeliveryAgent.insertMany([
      { name:'Raju K',   phone:'9111111111', email:'raju@hb.com',   vehicleType:'bike',    vehicleNumber:'KA25AB1234', isOnline:true,  isAvailable:true,  rating:4.8, totalDeliveries:245, currentLocation:{ lat:15.4589, lng:75.0078 } },
      { name:'Priya M',  phone:'9222222222', email:'priya@hb.com',  vehicleType:'scooter', vehicleNumber:'KA25CD5678', isOnline:true,  isAvailable:true,  rating:4.9, totalDeliveries:312, currentLocation:{ lat:15.4612, lng:75.0134 } },
      { name:'Suresh B', phone:'9333333333', email:'suresh@hb.com', vehicleType:'bike',    vehicleNumber:'KA25EF9012', isOnline:true,  isAvailable:true,  rating:4.6, totalDeliveries:178, currentLocation:{ lat:15.3647, lng:75.1240 } },
      { name:'Kavya R',  phone:'9444444444', email:'kavya@hb.com',  vehicleType:'scooter', vehicleNumber:'KA25GH3456', isOnline:true,  isAvailable:true,  rating:4.7, totalDeliveries:203, currentLocation:{ lat:15.3712, lng:75.1198 } },
      { name:'Mahesh T', phone:'9555555555', email:'mahesh@hb.com', vehicleType:'bike',    vehicleNumber:'KA25IJ7890', isOnline:false, isAvailable:false, rating:4.5, totalDeliveries:156, currentLocation:{ lat:15.3698, lng:75.1356 } },
    ]);
    console.log('✅ 5 Delivery agents created');

    console.log('\n🎉 Seed complete!');
    console.log('   Admin : admin@hungrybirds.com / admin123');
    console.log('   User  : test@test.com / test123');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err);
    process.exit(1);
  }
};

seed();